[build]
# Usamos SECRETS_SCAN_OMIT_KEYS para decirle a Netlify que no falle el build
# cuando encuentre estas variables, ya que son PUBLICAS por diseño.
environment = { SECRETS_SCAN_OMIT_KEYS = "NEXT_PUBLIC_SUPABASE_URL,NEXT_PUBLIC_SUPABASE_ANON_KEY" }